msg2 "from https://gist.github.com/myusuf3/7f645819ded92bda6677"
echo ""
msg2 "Delete the relevant section from the .gitmodules file."
msg2 "Stage the .gitmodules changes git add .gitmodules"
msg2 "Delete the relevant section from .git/config."
msg2 "Run git rm --cached path_to_submodule (no trailing slash)."
msg2 "Run rm -rf .git/modules/path_to_submodule (no trailing slash)."
msg2 "Commit git commit -m 'Removed submodule '"
msg2 "Delete the now untracked submodule files rm -rf path_to_submodule"